package com.facilityflow.entity;

public enum NotificationType {
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_CHANGED,
    TICKET_ESCALATED,
    RESERVATION_REQUESTED,
    RESERVATION_APPROVED,
    RESERVATION_REJECTED,
    RESERVATION_CANCELLED,
    ASSET_WARRANTY_EXPIRING,
    SYSTEM
}
